name: thiago's thoughts 
description: ramblings and scribblings
meta_description: "so meta"

markdown: redcarpet
pygments: true
logo: false
paginate: 15

# Details for the RSS feed generator
url:            'http://thiagofm.github.io'
author:         'Thiago Massa'
