name: thiago's thoughts
description: Programming, data science and stuff
meta_description: "so meta"

markdown: redcarpet
pygments: true
logo: false
paginate: 15

# Details for the RSS feed generator
url:            'http://thiago.fm'
author:         'Thiago FM'
