name: thiago's stuff
description: ruby, clojure, emacs, mech. keyboards...
meta_description: "so meta"

markdown: redcarpet
pygments: true
logo: false
paginate: 15

# Details for the RSS feed generator
url:            'http://thiagofm.github.io'
author:         'Thiago Massa'
